<a href="https://colab.research.google.com/github/Scanfmonse/ExamenCompiladores/blob/master/mineriacolab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos


##**Primer Parcial**

### Introducción


####1.1.1 Conceptos

La minería de datos es el proceso de extraer información útil a partir de una acumulación de datos, a menudo provenientes de un almacén o de una recopilación de data sets vinculados. Las herramientas para minería de datos incluyen potentes capacidades estadísticas, matemáticas y analíticas cuyo propósito principal es examinar grandes data sets para identificar tendencias, patrones y relaciones a fin de dar soporte a la toma de decisiones y planificación fundamentadas.

#### 1.1.2 Ciencia de datos

La ciencia de datos es un campo interdisciplinario que combina matemáticas, estadística, programación, inteligencia artificial (IA) y aprendizaje automático (machine learning) para analizar grandes volúmenes de datos estructurados y no estructurados. Su objetivo principal es extraer información valiosa que permita tomar decisiones estratégicas y resolver problemas empresariales.

In [1]:
In [1]: help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [18]:
L = [1, 2, 3]
L.insert?

In [19]:
L?

Iphyton Magic Comands

In [2]:
def donothing(x):
  return x

In [5]:
#El comando timeit sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

80.9 µs ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
#El comando %%timeit sirve tambien para evaluar solo que este abarca varias lineas de codigo en lugar de solo 1
%%timeit
L=[]
for n in range(1000):
  L.append(n**2)

94.4 µs ± 23.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [22]:
%timeit?

In [23]:
%%timeit?

IPython and Shell Commands

In [24]:
!ls

sample_data


In [29]:
%cd sample_data/

/content/sample_data


In [31]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [32]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [33]:
contents = !ls
print(contents)

['anscombe.json\t\t      mnist_test.csv', 'california_housing_test.csv   mnist_train_small.csv', 'california_housing_train.csv  README.md']


In [34]:
directory = !pwd

In [36]:
print(directory)

['/content/sample_data']


In [37]:
type(directory)

IPython.utils.text.SList

In [38]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '43d50b2509a7',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [40]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [41]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
import numpy as np

In [43]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [44]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [45]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [46]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [47]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])