<a href="https://colab.research.google.com/github/Scanfmonse/ExamenCompiladores/blob/master/mineriacolab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos


##**Primer Parcial**

### Introducción


####1.1.1 Conceptos

La minería de datos es el proceso de extraer información útil a partir de una acumulación de datos, a menudo provenientes de un almacén o de una recopilación de data sets vinculados. Las herramientas para minería de datos incluyen potentes capacidades estadísticas, matemáticas y analíticas cuyo propósito principal es examinar grandes data sets para identificar tendencias, patrones y relaciones a fin de dar soporte a la toma de decisiones y planificación fundamentadas.

#### 1.1.2 Ciencia de datos

La ciencia de datos es un campo interdisciplinario que combina matemáticas, estadística, programación, inteligencia artificial (IA) y aprendizaje automático (machine learning) para analizar grandes volúmenes de datos estructurados y no estructurados. Su objetivo principal es extraer información valiosa que permita tomar decisiones estratégicas y resolver problemas empresariales.

In [ ]:
In [1]: help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
L = [1, 2, 3]
L.insert?

In [ ]:
L?

Iphyton Magic Comands

In [ ]:
def donothing(x):
  return x

In [ ]:
#El comando timeit sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

80.9 µs ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#El comando %%timeit sirve tambien para evaluar solo que este abarca varias lineas de codigo en lugar de solo 1
%%timeit
L=[]
for n in range(1000):
  L.append(n**2)

94.4 µs ± 23.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
contents = !ls
print(contents)

['anscombe.json\t\t      mnist_test.csv', 'california_housing_test.csv   mnist_train_small.csv', 'california_housing_train.csv  README.md']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content/sample_data']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '43d50b2509a7',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

In [ ]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Basics of NumPy Arrays

In [2]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [6]:
print("dtype:", x3.dtype)

dtype: int64


In [7]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]

np.int64(5)

In [10]:
x1[4]

np.int64(7)

In [11]:
x1[-1]

np.int64(9)

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0, 0]

np.int64(3)

In [14]:
x2[0, 0] = 12

In [38]:
x2[2, 3] #Primero renglon y despues columna

np.int64(7)

In [15]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

Array Slicing: Accessing Subarrays

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [18]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]  # middle subarray

array([4, 5, 6])

In [20]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [21]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [22]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [26]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [27]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [28]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [29]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [30]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


In [31]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


#### Estadistica Básica